auth_server:
  host: geo-copilot-auth-server.buildnexai.com
  port: ''
  secret: mysecret
database:
  database: ../data/flet.db
plaxis:
  password: W@%4>RTT4N?Tf@@n
  plaxis_path: C:\Program Files\Bentley\Geotechnical\PLAXIS 2D CONNECT Edition V20\Plaxis2DXInput.exe
  port_i: '10000'
  port_o: '10001'
